# Generated by Django 5.1.6 on 2025-03-19 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_remove_customuser_full_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
